# Common Parameters for Wacht Backend API

parameters:
  # User parameters
  UserId:
    name: user_id
    in: path
    required: true
    schema:
      type: string
    description: User ID

  # Organization parameters
  OrganizationId:
    name: organization_id
    in: path
    required: true
    schema:
      type: string
    description: Organization ID

  # Workspace parameters
  WorkspaceId:
    name: workspace_id
    in: path
    required: true
    schema:
      type: string
    description: Workspace ID

  # AI parameters
  AgentId:
    name: agent_id
    in: path
    required: true
    schema:
      type: string
    description: AI Agent ID

  ToolId:
    name: tool_id
    in: path
    required: true
    schema:
      type: string
    description: AI Tool ID

  KnowledgeBaseId:
    name: kb_id
    in: path
    required: true
    schema:
      type: string
    description: Knowledge Base ID

  DocumentId:
    name: document_id
    in: path
    required: true
    schema:
      type: string
    description: Document ID

  IntegrationId:
    name: integration_id
    in: path
    required: true
    schema:
      type: string
    description: Integration ID

  ExecutionContextId:
    name: context_id
    in: path
    required: true
    schema:
      type: string
    description: Execution Context ID

  # Webhook parameters
  WebhookAppName:
    name: app_name
    in: path
    required: true
    schema:
      type: string
    description: Webhook app name

  WebhookEndpointId:
    name: endpoint_id
    in: path
    required: true
    schema:
      type: string
    description: Webhook endpoint ID

  WebhookDeliveryId:
    name: delivery_id
    in: path
    required: true
    schema:
      type: string
    description: Webhook delivery ID

  # API Key parameters
  ApiAuthAppName:
    name: app_name
    in: path
    required: true
    schema:
      type: string
    description: API Auth app name

  # Pagination parameters
  Limit:
    name: limit
    in: query
    schema:
      type: integer
      minimum: 1
      maximum: 100
      default: 50
    description: Number of items to return

  Offset:
    name: offset
    in: query
    schema:
      type: integer
      minimum: 0
      default: 0
    description: Number of items to skip

  Search:
    name: search
    in: query
    schema:
      type: string
    description: Search query
